# Generated by Django 5.0.6 on 2024-05-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Identifiant', models.CharField(max_length=50)),
                ('Mail', models.EmailField(max_length=254)),
                ('Nummber', models.CharField(max_length=50)),
            ],
        ),
    ]
