# Generated by Django 5.0.6 on 2024-05-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPress', '0002_client_depot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depot',
            name='Type_vêtements',
        ),
    ]
