# Generated by Django 5.0.6 on 2024-05-24 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPress', '0003_remove_depot_type_vêtements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Nummber',
            new_name='Number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Nummber',
            new_name='Number',
        ),
    ]
