# Generated by Django 5.0.6 on 2024-05-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPress', '0004_rename_nummber_client_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Adresse',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
