# Generated by Django 5.0.6 on 2024-06-05 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPress', '0005_user_adresse'),
    ]

    operations = [
        migrations.CreateModel(
            name='vetement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_vet', models.CharField(max_length=50)),
                ('nbr_vet', models.DateField()),
                ('id_depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPress.depot')),
            ],
        ),
    ]
