# Generated by Django 5.0.6 on 2024-06-05 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPress', '0006_vetement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depot',
            old_name='id_client',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='vetement',
            old_name='nom_vet',
            new_name='libelle',
        ),
        migrations.RemoveField(
            model_name='vetement',
            name='id_depot',
        ),
        migrations.RemoveField(
            model_name='vetement',
            name='nbr_vet',
        ),
        migrations.CreateModel(
            name='list_vetement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr_vet', models.DateField()),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPress.depot')),
                ('nom_vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPress.vetement')),
            ],
        ),
    ]
