# Generated by Django 5.0.6 on 2024-06-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPress', '0007_rename_id_client_depot_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_vetement',
            name='nbr_vet',
            field=models.IntegerField(),
        ),
    ]
