# Generated by Django 5.0.6 on 2024-06-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPress', '0009_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='type_traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
            ],
        ),
    ]
