# Generated by Django 5.0.6 on 2024-06-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPress', '0010_type_traitement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depot',
            name='client',
        ),
        migrations.RemoveField(
            model_name='list_vetement',
            name='depot',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.RemoveField(
            model_name='list_vetement',
            name='nom_vet',
        ),
        migrations.DeleteModel(
            name='type_traitement',
        ),
        migrations.DeleteModel(
            name='depot',
        ),
        migrations.DeleteModel(
            name='list_vetement',
        ),
        migrations.DeleteModel(
            name='vetement',
        ),
    ]
