# Generated by Django 5.0.6 on 2024-06-22 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPress', '0011_remove_depot_client_remove_list_vetement_depot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr_vet', models.IntegerField()),
                ('Prix', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPress.client')),
            ],
        ),
        migrations.CreateModel(
            name='depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('date_depot', models.DateField()),
                ('date_retrait', models.DateField(blank=True)),
                ('Regler', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPress.client')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPress.images')),
            ],
        ),
        migrations.CreateModel(
            name='vetement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPress.tarif')),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='type_vetements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPress.vetement'),
        ),
    ]
