# Generated by Django 5.0.6 on 2024-06-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPress', '0012_tarif_images_depot_vetement_images_type_vetements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
