# Generated by Django 5.0.6 on 2024-06-25 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPress', '0013_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depot',
            name='photo',
        ),
        migrations.CreateModel(
            name='depot_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPress.depot')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPress.images')),
            ],
        ),
    ]
