# Generated by Django 5.0.6 on 2024-06-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPress', '0015_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='date_retrait',
            field=models.DateField(blank=True, default=None),
        ),
    ]
