# Generated by Django 5.0.6 on 2024-06-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPress', '0016_alter_depot_date_retrait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='date_retrait',
            field=models.DateField(blank=True, null=True),
        ),
    ]
